@baseUrl = http://localhost:4000
@resourceName = api/products


GET {{baseUrl}}/{{resourceName}}
Content-Type: application/json

###

# @name filtersByPrice
GET {{baseUrl}}/{{resourceName}}?price_gte=10
Content-Type: application/json

###

# @name filterByCategory
GET {{baseUrl}}/{{resourceName}}?category=best seller

###

# @name updateProduct
PATCH  {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
  "body" : "le duc nghi 2"
}

###

# @name removeProduct
DELETE {{baseUrl}}/{{resourceName}}/2
